server:
  port: 8082
spring:
  application:
    name: chatserver
  cloud:
    nacos:
      discovery:
        # nacos 服务地址
        server-addr: 10.134.58.144:8848
        cluster-name: WH
  rabbitmq:
    host: 192.168.106.102
    # rabbit mq 端口
    port: 5672
    username: root
    password: root
    virtual-host: /